---
- name: Uninstall LXC (Debian/Ubuntu)
  apt:
    name: lxc
    state: absent
    purge: yes
  when: ansible_os_family == "Debian"
  tags: cleanup

- name: Remove additional LXC packages (Debian/Ubuntu)
  apt:
    name: "{{ item }}"
    state: absent
    purge: yes
  loop:
    - lxc-utils
    - lxc-templates
  when: ansible_os_family == "Debian"
  tags: cleanup

- name: Remove unused packages and clean up (Debian/Ubuntu)
  apt:
    autoremove: yes
    purge: yes
  when: ansible_os_family == "Debian"
  tags: cleanup

- name: Clean APT cache (Debian/Ubuntu)
  apt:
    autoclean: yes
  when: ansible_os_family == "Debian"
  tags: cleanup

- name: Uninstall LXC (RedHat/CentOS)
  yum:
    name: lxc
    state: absent
  when: ansible_os_family == "RedHat"
  tags: cleanup

- name: Remove additional LXC packages (RedHat/CentOS)
  yum:
    name: "{{ item }}"
    state: absent
  loop:
    - lxc-extra
    - lxc-templates
  when: ansible_os_family == "RedHat"
  tags: cleanup

- name: Clean YUM cache (RedHat/CentOS)
  command: yum clean all
  when: ansible_os_family == "RedHat"
  tags: cleanup

- name: Verify LXC is uninstalled
  command: which lxc
  register: lxc_check
  ignore_errors: yes
  tags: cleanup

- name: Debug LXC check result
  debug:
    msg: "LXC command is still available"
  when: lxc_check.rc == 0
  tags: cleanup

- name: Remove orphaned network interfaces
  shell: |
    for iface in $(ls /sys/class/net | grep -E 'br-|veth|lxcbr0'); do
      ip link delete $iface
    done
  ignore_errors: yes
  tags: cleanup



