---
- name: Stop and disable LXD service
  service:
    name: snap.lxd.daemon
    state: stopped
    enabled: no
  ignore_errors: yes
  tags: cleanup

- name: Uninstall LXD via Snap
  snap:
    name: lxd
    state: absent
  ignore_errors: yes
  tags: cleanup

- name: Remove LXD network lxdbr0
  command: lxc network delete lxdbr0
  ignore_errors: yes
  tags: cleanup

- name: Remove orphaned network interfaces
  shell: |
    for iface in $(ls /sys/class/net | grep -E 'br-|lxdbr0|veth'); do
      ip link delete $iface
    done
  ignore_errors: yes
  tags: cleanup

- name: Clear LXD configuration directory
  file:
    path: /var/snap/lxd/common/lxd
    state: absent
    recurse: yes
  ignore_errors: yes
  tags: cleanup





