version: 3

dotenv:
  - .env

includes:
  infrastructure:on-prem: ./infrastructure/on-prem/Taskfile.yaml
  gitops:on-prem: ./gitops/on-prem/Taskfile.yaml
  docker: ./docker/Taskfile.yaml
  applications: ./applications/Taskfile.yaml

tasks:
  default:
    desc: "List all available tasks"
    cmds:
      - task --list-all
    silent: true