# join_cluster.yml
---
- name: Check if server is already a cluster member
  shell: |
    lxc cluster show {{ inventory_hostname }}
  register: node_check
  ignore_errors: true

- name: Set fact if server is already a cluster member
  set_fact:
    node_already_member: "{{ node_check.rc == 0 }}"

- name: Retrieve and format cluster certificate from bootstrap server
  command: sed ':a;N;$!ba;s/\n/\n\n/g' /var/snap/lxd/common/lxd/cluster.crt
  register: cluster_cert
  delegate_to: "{{ groups['bootstrap_server'][0] }}"
  run_once: true

- name: Save cluster certificate to a fact
  set_fact:
    cluster_certificate: "{{ cluster_cert.stdout }}"

- name: Create join preseed file
  template:
    src: join_preseed.yml.j2
    dest: /tmp/join_preseed.yml
  when:
    - inventory_hostname in groups['member_servers']
    - not node_already_member

- name: Join LXD cluster with preseed
  shell: |
    lxd init --preseed < /tmp/join_preseed.yml
  when:
    - inventory_hostname in groups['member_servers']
    - not node_already_member





