---
- name: Check if Snap is installed
  command: which snap
  register: snap_installed
  ignore_errors: yes

- name: Ensure Snapd is installed (Debian/Ubuntu)
  apt:
    name: snapd
    state: present
  when:
    - ansible_os_family == "Debian"
    - snap_installed.rc != 0

- name: Ensure Snapd is installed (RedHat/CentOS/Fedora)
  yum:
    name: snapd
    state: present
  when:
    - ansible_os_family == "RedHat"
    - snap_installed.rc != 0

- name: Enable and start Snapd service (RedHat/CentOS/Fedora)
  systemd:
    name: snapd
    state: started
    enabled: yes
  when:
    - ansible_os_family == "RedHat"
    - snap_installed.rc != 0

- name: Create symbolic link for Snap (RedHat/CentOS/Fedora)
  file:
    src: /var/lib/snapd/snap
    dest: /snap
    state: link
    force: yes
  when:
    - ansible_os_family == "RedHat"
    - snap_installed.rc != 0

- name: Enable and start Snapd socket (Debian/Ubuntu)
  systemd:
    name: snapd.socket
    state: started
    enabled: yes
  when:
    - ansible_os_family == "Debian"
    - snap_installed.rc != 0

- name: Ensure Snap's bin directory is in the PATH for all users
  lineinfile:
    path: /etc/profile.d/snap.sh
    line: 'export PATH=$PATH:/snap/bin'
    create: yes
    state: present

- name: Ensure Snap's bin directory is in the current shell PATH
  shell: '. /etc/profile.d/snap.sh'
  when: snap_installed.rc != 0

- name: Install Snap core if not already installed
  shell: snap install core
  when: snap_installed.rc != 0

- name: Install LXD via Snap
  snap:
    name: lxd
    state: present

- name: Start and enable LXD service (Snap)
  service:
    name: snap.lxd.daemon
    state: started
    enabled: yes

- name: Ensure Snap's bin directory is in the PATH for sudo
  lineinfile:
    path: /etc/sudoers.d/snap
    line: 'Defaults secure_path="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin:/snap/bin"'
    create: yes
    state: present




