# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket         = "klustered.us"
    dynamodb_table = "klustered.us-lock-table"
    encrypt        = true
    key            = "01-k3s-cluster/03-configure-dns/terraform.tfstate"
    region         = "us-east-1"
  }
}
