VERSION 0.7

plan-01-nas-server:
    FROM ghcr.io/stevenbuglione/build-image:latest

    COPY . /app
    WORKDIR /app/live/01-nas-services

    RUN \
        --secret OP_SERVICE_ACCOUNT_TOKEN \
        chmod +x /app/live/01-nas-services/op-secrets.sh && \
        source ./op-secrets.sh && \
        terragrunt run-all plan

apply-01-nas-server:
    FROM ghcr.io/stevenbuglione/build-image:latest

    COPY . /app
    WORKDIR /app/live/01-nas-services

    RUN \
        --secret OP_SERVICE_ACCOUNT_TOKEN \
        chmod +x /app/live/01-nas-services/op-secrets.sh && \
        source ./op-secrets.sh && \
        terragrunt run-all apply --non-interactive


destroy-01-nas-server:
    FROM ghcr.io/stevenbuglione/build-image:latest

    COPY . /app
    WORKDIR /app/live/01-nas-services

    RUN \
        --secret OP_SERVICE_ACCOUNT_TOKEN \
        chmod +x /app/live/01-nas-services/op-secrets.sh && \
        source ./op-secrets.sh && \
        terragrunt run-all destroy --non-interactive


