VERSION 0.7


reconfigure-01-nas-server:
    FROM ghcr.io/stevenbuglione/build-image:latest

    COPY . /app
    WORKDIR /app/live/01-nas-services

    RUN \
        --secret OP_SERVICE_ACCOUNT_TOKEN \
        chmod +x ./op-secrets.sh && \
        source ./op-secrets.sh && \
        terragrunt run-all init -reconfigure

plan-01-nas-server:
    FROM ghcr.io/stevenbuglione/build-image:latest

    COPY . /app
    WORKDIR /app/live/01-nas-services

    RUN \
        --secret OP_SERVICE_ACCOUNT_TOKEN \
        chmod +x ./op-secrets.sh && \
        source ./op-secrets.sh && \
        terragrunt run-all plan

apply-01-nas-server:
    FROM ghcr.io/stevenbuglione/build-image:latest

    COPY . /app
    WORKDIR /app/live/01-nas-services

    RUN \
        --secret OP_SERVICE_ACCOUNT_TOKEN \
        chmod +x ./op-secrets.sh && \
        source ./op-secrets.sh && \
        terragrunt run-all apply --non-interactive


destroy-01-nas-server:
    FROM ghcr.io/stevenbuglione/build-image:latest

    COPY . /app
    WORKDIR /app/live/01-nas-services

    RUN \
        --secret OP_SERVICE_ACCOUNT_TOKEN \
        chmod +x ./op-secrets.sh && \
        source ./op-secrets.sh && \
        terragrunt run-all destroy --non-interactive

reconfigure-02-kubernetes:
    FROM ghcr.io/stevenbuglione/build-image:latest

    ENV OP_CONNECT_HOST="http://10.10.10.7:8080"

    COPY . /app
    WORKDIR /app/live/02-kubernetes/dev

    RUN \
        --secret OP_SERVICE_ACCOUNT_TOKEN \
        chmod +x ./op-secrets.sh && \
        source ./op-secrets.sh && \
        terragrunt run-all init -reconfigure

plan-02-kubernetes:
    FROM ghcr.io/stevenbuglione/build-image:latest

    ENV OP_CONNECT_HOST="http://10.10.10.7:8080"

    COPY . /app
    WORKDIR /app/live/02-kubernetes/dev

    RUN \
        --secret OP_SERVICE_ACCOUNT_TOKEN \
        chmod +x ./op-secrets.sh && \
        source ./op-secrets.sh && \
        terragrunt run-all plan

apply-02-kubernetes:
    FROM ghcr.io/stevenbuglione/build-image:latest

    ENV OP_CONNECT_HOST="http://10.10.10.7:8080"

    COPY . /app
    WORKDIR /app/live/02-kubernetes/dev

    RUN \
        --secret OP_SERVICE_ACCOUNT_TOKEN \
        chmod +x ./op-secrets.sh && \
        source ./op-secrets.sh && \
        terragrunt run-all apply --non-interactive


destroy-01-nas-server:
    FROM ghcr.io/stevenbuglione/build-image:latest

    ENV OP_CONNECT_HOST="http://10.10.10.7:8080"

    COPY . /app
    WORKDIR /app/live/02-kubernetes/dev

    RUN \
        --secret OP_SERVICE_ACCOUNT_TOKEN \
        chmod +x ./op-secrets.sh && \
        source ./op-secrets.sh && \
        terragrunt run-all destroy --non-interactive


