version: 3

tasks:
  default:
    desc: "List all available tasks"
    cmds:
      - task --list-all
    silent: true

  build:
    desc: "Build Docker CI/CD Build image"
    dir: '{{.ROOT_DIR}}/devops/on-prem/docker'
    cmds:
      - >
        docker build
        --build-arg ALPINE_VERSION={{.ALPINE_VERSION}}
        --build-arg OPEN_TOFU_VERSION={{.OPEN_TOFU_VERSION}}
        --build-arg TERRAGRUNT_VERSION={{.TERRAGRUNT_VERSION}}
        -t {{.BUILD_IMAGE_NAME}}:{{.IMAGE_VERSION}}
        -t {{.BUILD_IMAGE_NAME}}:latest
        -f ./build-image/Dockerfile
        ./build-image
    env:
      DOCKER_BUILDKIT: 1

