# Generated by Terragrunt. Sig: nIlQXj57tbuaRZEa
terraform {
  backend "s3" {
    bucket                      = "klustered.us"
    encrypt                     = false
    endpoint                    = "http://10.10.10.7:9769"
    force_path_style            = true
    key                         = "02-kubernetes/01-k3s-cluster/terraform.tfstate"
    region                      = "us-east-1"
    skip_credentials_validation = true
  }
}
