all:
  children:
    lxd_cluster:
      children:
        bootstrap_server:  # Primary server that initializes the cluster
          hosts:
            pluto:
              ansible_host: 10.10.10.5
              server_name: pluto
        member_servers:    # Secondary servers that join the existing cluster
          hosts:
            neptune:
              ansible_host: 10.10.10.3
              server_name: neptune
            saturn:
              ansible_host: 10.10.10.4
              server_name: saturn
            earth:
              ansible_host: 10.10.10.6
              server_name: earth
  vars:
    ansible_user: sbuglione
    ansible_ssh_private_key_file: ~/.ssh/ansible-key
    lxd_cluster_password: "{{ lookup('env', 'LXD_CLUSTER_PASSWORD') | default('password', true) }}"
    lxd_cluster_address: 10.10.10.10/24
    lxd_cluster_name: klustered
    lxd_cluster_cert: "{{ lookup('env', 'LXD_CLUSTER_CI_CERT') | default('your toast if this hits', true) }}"
    lxd_cluster_cert_name: "{{ lookup('env', 'LXD_CLUSTER_CERT_NAME') | default('terraform-ci-client', true) }}"
    bootstrap_address: "{{ hostvars[groups['bootstrap_server'][0]]['ansible_host'] }}"








